### ISSUE TITLE
No module named 'videoUtils'

### ISSUE THREAD

**Issue by atzoriandrea** [tau-adl/Detection_Tracking_JetsonTX2#1]
Sorry, but I can't find how to include the videoUtils module, which is not present.

Thanks in advance!

**Comment by Boinet** [comment]
Hi atzoriandrea, 
Thanks for your interest in the project. 
Indeed the file was missing. It has now been uploaded. 
Best regards,

**Comment by Boinet** [comment]
closing issue. Feel free to reopen if needed.
