### ISSUE TITLE
Expo884FPS20.mp4 test video

### ISSUE THREAD

**Issue by silent-code** [tau-adl/Detection_Tracking_JetsonTX2#2]
Hi is there a way I could get the Expo884FPS20.mp4 video you used for testing? I'd like to use it to test the algorithm on a Xavier NX. Thanks in advance!

**Comment by Boinet** [comment]
Hi silent-code, 
Thanks for your interest in our project. 
Here is a link to our Expo 884FPS20 video. https://we.tl/t-ci4H1RXvoR


Do not hesitate if you have more questions.

**Comment by silent-code** [comment]
Thanks so much!

**Comment by MuhammadAsadJaved** [comment]
@silent-code  Have you tested the models? Does it work for you?

**Comment by gzc-123456-gzc** [comment]
@Boinet Can you resend the URL of this video?  I think it has expired, thank you

**Comment by silent-code** [comment]
@MuhammadAsadJaved thanks for the video link. yes it appears to work however, i believe it will require minor tuning in my setup since the tracker resets periodically during the video.

**Comment by gzc-123456-gzc** [comment]
@silent-code  Friends, can you send me a link to the video?  Thanks a lot

**Comment by MuhammadAsadJaved** [comment]
This is another almost same video you can try it.  
@gzc-123456-gzc 

https://drive.google.com/file/d/1lzfKA-kNeKm268z-zYWqnE0bgz92l32u/view?usp=sharing
