### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by GOBish** [tau-adl/Detection_Tracking_JetsonTX2#5]
Thank you for sharing this code!
Would there be any chance you have a python version as well?

**Comment by MuhammadAsadJaved** [comment]
@GOBish  He used Python3 in the runme.sh , that's mean python3 is used for the project, however not sure about 3.xxx , I am trying with 3.6.

**Comment by GOBish** [comment]
Thanks - I see that everything is in python now. For some reason I could swear that last time I looked it was all in C.
