### ISSUE TITLE
Where are weights??

### ISSUE THREAD

**Issue by berkantay** [tau-adl/Detection_Tracking_JetsonTX2#8]
I could not find the weights of the model.

**Comment by gzc-123456-gzc** [comment]
@berkantay This should be downloaded from the URL given by the author

**Comment by gzc-123456-gzc** [comment]
@berkantay  ，hello,Do you have these two videos here?   Trim840.mp4  and Expo884FPS20.mp4

**Comment by berkantay** [comment]
> @berkantay This should be downloaded from the URL given by the author

Which link are you talking about .caffemodel link??

**Comment by gzc-123456-gzc** [comment]
@berkantay  http ://cs.stanford.edu/people/davheld/public/GOTURN/weights_init/tracker_init.caffemodel
